[package]
name = "energetium"
version = "0.0.1"
entrypoint = "lib.typ"
authors = [
    "Typsium Community <https://github.com/Typsium>",
    "β-吲哚基丙氨酸 <https://github.com/tryptophawa>",
]
license = "MIT"
description = "Calculate chemistry energetics and kinetics equations with WebAssembly acceleration."
repository = "https://github.com/Typsium/Energetium"
keywords = ["chemistry", "thermodynamics", "kinetics", "energetics", "calculations", "wasm"]
categories = ["visualization", "scripting"]
disciplines = ["chemistry", "physics"]
compiler = "0.12.0"
exclude = ["wasm/target/", "*.wasm.map", "examples/"]
